

management:
  shell:
    auth:
      simple:
        user:
          name: BalterNotz
          password: BalterNotz
      type: simple
    ssh:
      port: 2003
      enabled: true
server:
  port: 58083